package org.easy.schulte.core.model

data class SchulteState(
  val selectedGrid: GridSpec = GridSpec.Five,
  val selectedAgeGroup: AgeGroup = AgeGroup.Adult,
  val selectedMarkMode: MarkMode = MarkMode.BriefFeedbackOnly,
  val numbers: List<Int> = emptyList(),
  val currentTarget: Int = 1,
  val completedNumbers: Set<Int> = emptySet(),
  val elapsedMillis: Long = 0L,
  val errorCount: Int = 0,
  val lastFeedback: CellFeedback? = null,
  val report: TrainingReport? = null,
  val aiSettings: AiSettings = AiSettings(),
  val apiKeyVisible: Boolean = false,
  val settingsMessage: SettingsMessage? = null,
  val aiAnalysis: AiAnalysis? = null,
  val aiAnalysisState: AiAnalysisState = AiAnalysisState.Idle,
  val records: List<TrainingRecord> = emptyList(),
  val recordSummary: TrainingRecordSummary = TrainingRecordSummary(),
  val progressComparison: ProgressComparison? = null,
  val recordGridFilter: RecordGridFilter = RecordGridFilter.All,
  val recordModeFilter: RecordModeFilter = RecordModeFilter.All,
  val recordTimeFilter: RecordTimeFilter = RecordTimeFilter.All,
  val showClearRecordsDialog: Boolean = false,
)
